### ISSUE TITLE
exporter hitting exceptions when parsing data from neuvector API

### ISSUE THREAD

**Issue by dadicool** [neuvector/prometheus-exporter#8]
We're using the neuvector prometheus exporter to expose the container scanning data into our monitoring infrastructure (p8s + grafana). It seems to work but it keeps reporting this exception in the logs over and over.

``` 
----------------------------------------
 Exception happened during processing of request from ('10.42.6.76', 54776)
 Traceback (most recent call last):
   File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
     self.finish_request(request, client_address)
   File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
     self.RequestHandlerClass(request, client_address, self)
   File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
     self.handle()
   File "/usr/lib/python3.7/http/server.py", line 426, in handle
     self.handle_one_request()
   File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
     method()
   File "/usr/lib/python3.7/site-packages/prometheus_client/exposition.py", line 152, in do_GET
     output = encoder(registry)
   File "/usr/lib/python3.7/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
     for metric in registry.collect():
   File "/usr/lib/python3.7/site-packages/prometheus_client/registry.py", line 75, in collect
     self.finish_request(request, client_address)
   File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
     self.RequestHandlerClass(request, client_address, self)
   File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
     self.handle()
   File "/usr/lib/python3.7/http/server.py", line 426, in handle
     self.handle_one_request()
   File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
     method()
   File "/usr/lib/python3.7/site-packages/prometheus_client/exposition.py", line 152, in do_GET
     output = encoder(registry)
   File "/usr/lib/python3.7/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
     for metric in registry.collect():
   File "/usr/lib/python3.7/site-packages/prometheus_client/registry.py", line 75, in collect
     for metric in collector.collect():
   File "/usr/local/bin/nv_exporter.py", line 84, in collect
     0] + ':' + dt3[1] + ':' + dt4[0] + ap
 TypeError: can only concatenate str (not "int") to str
 ----------------------------------------
```

Not sure what this indicates but it seems that not all data provided in the neuvector API is getting exposed as p8s metrics.

**Comment by becitsthere** [comment]
Time string parsing logic has been updated in the latest PR.

**Comment by garyduan** [comment]
Resolved
